const all_orders = [
    {
        id: "#1236",
        date: "5 Mar, 10:20 AM",
        date_visit: "3 Mar, 11:200 AM",
        email: "michael.lawson@reqres.in",
        first_name: "Michael",
        last_name: "Lawson",
        avatar: "https://reqres.in/img/faces/7-image.jpg",
        product: "Phone Case Pink  x 2",
        price: "50,00",
        status: "Okay",
        trend: "down"
    },
    {
        id: "#1235",
        date: "17 Mar, 12:00 PM",
        date_visit: "14 Mar, 11:00 AM",
        email: "lindsay.ferguson@reqres.in",
        first_name: "Lindsay",
        last_name: "Ferguson",
        avatar: "https://reqres.in/img/faces/8-image.jpg",
        product: "Valvet T-shirt",
        price: "55,50",
        status: "Follow up",
        trend: "down"
    },
    {
        id: "#1234",
        date: "16 Mar, 1:00 PM",
        date_visit: "12 Mar, 10:00 AM",
        email: "tobias.funke@reqres.in",
        first_name: "Tobias",
        last_name: "Funke",
        avatar: "https://reqres.in/img/faces/9-image.jpg",
        product: "Nike Sport V2",
        price: "140,20",
        status: "Okay",
        trend: "up"
    },
    {
        id: "#1233",
        date: "10 Mar, 2:20 PM",
        date_visit: "10 Mar, 12:00 PM",
        email: "byron.fields@reqres.in",
        first_name: "Byron",
        last_name: "Fields",
        avatar: "https://reqres.in/img/faces/10-image.jpg",
        product: "Nike Sport V2",
        price: "140,20",
        status: "Okay",
        trend: "down"
    },
    {
        id: "#1232",
        date: "17 Mar, 8:30 AM",
        date_visit: "8 Mar, 11:00 PM",
        email: "george.edwards@reqres.in",
        first_name: "George",
        last_name: "Edwards",
        avatar: "https://reqres.in/img/faces/11-image.jpg",
        product: "Nike Sport V2",
        price: "140,20",
        status: "Follow up",
        trend: "up"
    },
    {
        id: "#1231",
        date: "18 Mar, 9:00 AM",
        date_visit: "12 Mar, 3:00 PM",
        email: "rachel.howell@reqres.in",
        first_name: "Rachel",
        last_name: "Howell",
        avatar: "https://reqres.in/img/faces/12-image.jpg",
        product: "Nike Sport V2",
        price: "140,20",
        status: "Okay",
        trend: "up"
    },
    {
        id: "#1236",
        date: "14 Mar, 10:20 AM",
        date_visit: "17 Mar, 11: 00 AM",
        email: "michael.lawson@reqres.in",
        first_name: "Michael",
        last_name: "Lawson",
        avatar: "https://reqres.in/img/faces/7-image.jpg",
        product: "Phone Case Pink  x 2",
        price: "50,00",
        status: "Okay",
        trend: "down"
    },
    {
        id: "#1235",
        date: "1 Mar, 10:00 AM",
        date_visit: "9 Mar, 3: 00 PM",
        email: "lindsay.ferguson@reqres.in",
        first_name: "Lindsay",
        last_name: "Ferguson",
        avatar: "https://reqres.in/img/faces/8-image.jpg",
        product: "Valvet T-shirt",
        price: "55,50",
        status: "Follow up",
        trend: "up"
    },
    {
        id: "#1234",
        date: "3 Mar, 10:20 AM",
        date_visit: "7 Mar, 11:200 AM",
        email: "tobias.funke@reqres.in",
        first_name: "Tobias",
        last_name: "Funke",
        avatar: "https://reqres.in/img/faces/9-image.jpg",
        product: "Nike Sport V2",
        price: "140,20",
        status: "Okay",
        trend: "up"
    },
    {
        id: "#1233",
        date: "8 Mar, 10:20 AM",
        date_visit: "10 Mar, 11:200 AM",
        email: "byron.fields@reqres.in",
        first_name: "Byron",
        last_name: "Fields",
        avatar: "https://reqres.in/img/faces/10-image.jpg",
        product: "Nike Sport V2",
        price: "140,20",
        status: "Okay",
        trend: "up"
    }
]

export default all_orders;